### ISSUE TITLE
When using 'sudo apt-get update", "Writing more data than expected (631844 > 631714)" error happens!

### ISSUE THREAD

**Issue by HomeLH** [RobertCNelson/ti-linux-kernel-dev#26]
debian@beaglebone:~$ sudo apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease                                                                             
Hit:2 http://ftp.debian.org/debian stretch-backports InRelease                                                                         
Get:3 http://repos.rcn-ee.com/debian stretch InRelease [3,058 B]                                                              
Ign:4 http://ftp.us.debian.org/debian stretch InRelease                         
Hit:5 http://ftp.us.debian.org/debian stretch-updates InRelease                 
Hit:6 http://ftp.us.debian.org/debian stretch Release
Get:7 http://124.202.164.13/files/211600000C58CC15/httpredir.debian.org/debian stretch/main armhf Packages [632 kB]                    
Err:7 http://124.202.164.13/files/211600000C58CC15/httpredir.debian.org/debian stretch/main armhf Packages                             
  Writing more data than expected (631844 > 631714)
  Hashes of expected file:
   - Filesize:631714 [weak]
   - SHA256:315e3dc6686d1f9c4386348f402b9729fcd4d8aed8f8895bcaebf759ade0766f
   - SHA1:1701a3a49ecdb66a4d3cbb9e24eda4d5f6a96f48 [weak]
   - MD5Sum:98137548a7dfd88b9a6549829356c030 [weak]
  Release file created at: Fri, 17 Aug 2018 03:06:00 +0000
Fetched 3,058 B in 35s (85 B/s)                                                                                                        
Reading package lists... Done
E: Failed to fetch http://124.202.164.13/files/211600000C58CC15/httpredir.debian.org/debian/dists/stretch/main/binary-armhf/Packages.gz  Writing more data than expected (631844 > 631714)
   Hashes of expected file:
    - Filesize:631714 [weak]
    - SHA256:315e3dc6686d1f9c4386348f402b9729fcd4d8aed8f8895bcaebf759ade0766f
    - SHA1:1701a3a49ecdb66a4d3cbb9e24eda4d5f6a96f48 [weak]
    - MD5Sum:98137548a7dfd88b9a6549829356c030 [weak]
   Release file created at: Fri, 17 Aug 2018 03:06:00 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by RobertCNelson** [comment]
@HomeLH we don't use "httpredir.debian.org" anymore, change it to: deb.debian.org

It's still a mirror network, so their cane be delays...

Regards,

**Comment by HomeLH** [comment]
Thank you very much! Could you tell the detailed method to change the"httpredir.debian.org".

**Comment by RobertCNelson** [comment]
```bash
sudo nano /etc/apt/sources.list
```

**Comment by HomeLH** [comment]
```
debian@beaglebone:~$ cat /etc/apt/sources.list
deb http://ftp.us.debian.org/debian stretch main contrib non-free
#deb-src http://deb.debian.org/debian stretch main contrib non-free

deb http://ftp.us.debian.org/debian stretch-updates main contrib non-free
#deb-src http://deb.debian.org/debian stretch-updates main contrib non-free

deb http://security.debian.org/ stretch/updates main contrib non-free
#deb-src http://deb.debian.org/debian-security stretch/updates main contrib non-free

deb http://ftp.debian.org/debian stretch-backports main contrib non-free
##deb-src http://deb.debian.org/debian stretch-backports main contrib non-free

#Kernel source (repos.rcn-ee.com) : https://github.com/RobertCNelson/linux-stable-rcn-ee
#
#git clone https://github.com/RobertCNelson/linux-stable-rcn-ee
#cd ./linux-stable-rcn-ee
#git checkout `uname -r` -b tmp
#
deb [arch=armhf] http://repos.rcn-ee.com/debian/ stretch main 
#deb-src [arch=armhf] http://repos.rcn-ee.com/debian/ stretch main
debian@beaglebone:~$ 
```
Here is my sources.list. I still can not revise it.
