### ISSUE TITLE
BBB dts for KEY_POWER

### ISSUE THREAD

**Issue by ghost** [RobertCNelson/ti-linux-kernel-dev#32]
I installed the kernel and such using the Debian packages.
I have the new 108 kernel and  The gpio_keys looks is builtin. I need to disable the power KEY_POWER button. Which dts I should go in and commented out.
Thank you.

**Comment by RobertCNelson** [comment]
Neither...

it's registered via: drivers/input/misc/tps65218-pwrbutton.c

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/input/misc/tps65218-pwrbutton.c#n76
