### ISSUE TITLE
Build specific kernel version

### ISSUE THREAD

**Issue by fakufaku** [RobertCNelson/ti-linux-kernel-dev#4]
Hi, I am trying to build a specific kernel version (e.g. 4.4.9). Somehow, I only manage to build the version at the HEAD of the linux-stable repo (4.4.19 now). Is it possible to do that ?

Thanks and best.

**Comment by RobertCNelson** [comment]
not in this repo..

Use https://github.com/RobertCNelson/yakbuild

read the readme.md

**Comment by fakufaku** [comment]
Ah! Sorry for that! I noticed after posting...
