### ISSUE TITLE
rcu_preempt detected stalls on CPUs/tasks

### ISSUE THREAD

**Issue by loserisme** [RobertCNelson/ti-linux-kernel-dev#52]
I build 4.14.108-ti-xenomai-r143 and  Ubuntu18.04 on Beaglebone AI. and i compiled IGH,when i start ethercat and scan slaves,it works well.but when i using the xenomai example in IGH .system will get stuck.i have no idea about it
![图片](https://user-images.githubusercontent.com/40932338/168535845-ba002167-228f-4be3-ad28-ebce782c92a4.png)

**Comment by RobertCNelson** [comment]
Feel free to report this to the xenomai list..
